blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/artf/grapesjs/discussions/new?category=ideas
    about: 'Suggest any ideas you have using our discussion forums.'
  - name: ğŸ™ Help
    url: https://github.com/artf/grapesjs/discussions/new?category=q-a
    about: 'If you have a question or need help, ask a question on the discussion forums.'
  - name: ğŸ“¢ Show and tell
    url: https://github.com/artf/grapesjs/discussions/new?category=show-and-tell
    about: "Have something nice to say or share about GrapesJS? We'd love to hear it!"